#!/bin/bash

# AUR \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si

PARU=/etc/paru.conf
sudo sed -i 's/^#BottomUp/BottomUp/g' $PARU

# pacman \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
PACMAN=/etc/pacman.conf
sudo sed -i 's/^#Color/Color/g' $PACMAN
sudo sed -i '/^#\[multilib\]/i\
[multilib]\
Include = /etc/pacman.d/mirrorlist\
' $PACMAN

# swap \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
sudo echo "zram-size = ram" >> /etc/systemd/zram-generator.conf

# shell: fish \\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -S fish
chsh -s /bin/fish $USER
