#!/bin/bash

# AUR \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si

#PARU=/etc/paru.conf
#sudo sed -i 's/^#BottomUp/BottomUp/g' $PARU

# pacman \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
PACMAN=/etc/pacman.conf
sudo sed -i 's/^#Color/Color/g' $PACMAN
sudo sed -i '/^#\[multilib\]/i\
[multilib]\
Include = /etc/pacman.d/mirrorlist\
' $PACMAN
yay -Syyu

# swap \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# sudo echo "zram-size = ram" >> /etc/systemd/zram-generator.conf

# shell: fish \\\\\\\\\\\\\\\\\\\\\\\\\\\
yay -S fish
chsh -s /bin/fish $USER
