#!bash
paru -S cloudflared nginx syncthing openlist-bin


# Services \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

# Openlist
read -r -p "Openlist Admin Password: " OPENLIST_PASSWORD
sudo -u openlist openlist admin set ${OPENLIST_PASSWORD} --data /var/lib/openlist
sudo systemctl enable --now openlist

# Cloudflared
echo "Please Manually Set Cloudflared"

# Syncthing
SYNCTHING=$HOME/.local/state/syncthing/config.xml
sed -i 's/127.0.0.1/0.0.0.0/g' $SYNCTHING
echo "Please Set Up Synching Urself"

# Nginx
echo "wait"
