#!/bin/bash

# Packages \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -S ly \
noto-fonts noto-fonts-cjk noto-fonts-emoji \
xdg-desktop-portal-gtk xdg-desktop-portal-gnome niri kitty xwayland-satellite \
noctalia-shell cliphist matugen cava wlsunset power-profiles-daemon ddcutil \
swayidle \
fcitx5-im fcitx5-chinese-addons fcitx5-pinyin-zhwiki fcitx5-breeze


# Configurations \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

## niri \\\\\\\\\\\\\\\\\\\\\\\\\\\\\
mkdir -p $HOME/.config/niri
cp /usr/share/doc/niri/default-config.kdl $HOME/.config/niri/config.kdl 
NIRI=$HOME/.config/niri/config.kdl 

### Delete \\\\\\\\\\\\\\\
sed -i '/^\s*\/\//d' "$@" $NIRI  # Delete comments
sed -i 's/waybar/d' $NIRI 
sed -i 's/fuzzel/d' $NIRI
sed -i 's/swaylock/d' $NIRI 

### Insert&Append \\\\\\\\\\\
sed -i '/output "eDP-1"/i\
output "PNP(SAC) N50pro 6 0x00000001" {\
    mode "1920x1080@120.000"\
    scale 1\
    transform "normal"\
    position x=0 y=0\
    focus-at-startup\
    }\
\
output "eDP-1" {\
    mode "1920x1080@60.052"\
    scale 1.25\
    transform "normal"\
    position x=0 y=1080\
    }\
' $NIRI

sed -i 's/alacritty/kitty/g' $NIRI
sed -i '/kitty/i\
    Mod+D { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "launcher" "toggle"; }\
    Mod+Alt+P { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "controlCenter" "toggle"; }\
    Mod+Alt+O { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "settings" "toggle"; }\
    Mod+Alt+L { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "lockScreen" "lock"; }
' $NIRI

cat << EOF >> $NIRI
window-rule {
  geometry-corner-radius 20
  clip-to-geometry true
}
debug {
  honor-xdg-activation-with-invalid-serial
}
layer-rule {
  match namespace="^noctalia-overview*"
  place-within-backdrop true
}
cursor {
    hide-when-typing
}
prefer-no-csd
spawn-at-startup "qs" "-c" "noctalia-shell"
spawn-at-startup "swayidle" "-w" "timeout" "300" "qs -c noctalia-shell ipc call lockScreen lock" "timeout" "600" "systemctl suspend" "before-sleep" "qs -c noctalia-shell ipc call lockScreen lock"
EOF

sudo echo "QT_QPA_PLATFORMTHEME=gtk3" >> /etc/environment

cp ./resources/face $HOME/.face
mkdir -p $HOME/Pictures/Wallpapers
cp ./resources/wallpaper.png $HOME/Pictures/Wallpapers

## Input \\\\\\\\\\\\\\\\\\\\\\\\\\\\
sudo cat << EOF >> /etc/environment
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
EOF

# Services \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
systemctl enable ly
