#!/bin/bash


# Daily Use \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
yay -Syyu
yay -S zen-browser-bin \
obsidian \
spotify \
steam \
wechat-bin \
#libnotify onlyoffice-bin

# Browser Cookies \\\\\\\\\\\\\\\\\\\\\\\\\\
