#!/bin/bash


# Daily Use \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -Syyu
paru -S zen-browser-bin \
obsidian \
spotify \
steam \
wechat-bin \
libnotify onlyoffice-bin

# Browser Cookies \\\\\\\\\\\\\\\\\\\\\\\\\\
