#!/bin/bash


# Daily Use \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -S zen-browser-bin \
syncthing \
obsidian \
spotify \
wechat-bin \
libnotify onlyoffice-bin

# Browser Cookies \\\\\\\\\\\\\\\\\\\\\\\\\\
