#!/bin/bash

# Input Method \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -S fcitx5-im \
fcitx5-chinese-addons fcitx5-pinyin-zhwiki \
fcitx5-breeze

# Daily Use \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -S zen-browser-bin \
syncthing \
obsidian \
spotify \
wechat-bin \
libnotify onlyoffice-bin

# Synching \\\\\\\\\\\\\\\\\\\\\\\\\\\\\






# Browser Cookies \\\\\\\\\\\\\\\\\\\\\\\\\\
