#!/bin/bash

# Packages \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
paru -S ly xdg-desktop-portal-gtk xdg-desktop-portal-gnome niri kitty xwayland-satellite \
noctalia-shell cliphist matugen cava wlsunset power-profiles-daemon ddcutil 


# Configurations \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
wget -O niri_config https://raw.githubusercontent.com/YaLTeR/niri/refs/heads/main/resources/default-config.kdl
NIRI=niri_config

# Delete
sed -i '/^\s*\/\//d' "$@" $NIRI  # Delete comments
sed -i 's/fuzzel/d' $NIRI
sed -i 's/swaylock/d' $NIRI 

# Insert&Append
sed -i '/output "eDP-1"/i\
output "PNP(SAC) N50pro 6 0x00000001" {\
    mode "1920x1080@120.000"\
    scale 1\
    transform "normal"\
    position x=0 y=0\
    focus-at-startup\
    }\
\
output "eDP-1" {\
    mode "1920x1080@60.052"\
    scale 1.25\
    transform "normal"\
    position x=0 y=1080\
    }\
' $NIRI

sed -i 's/alacritty/kitty/g' $NIRI
sed -i '/kitty/i\
    Mod+D { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "launcher" "toggle"; }\
    Mod+Alt+P { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "controlCenter" "toggle"; }\
    Mod+Alt+O { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "settings" "toggle"; }\
    Mod+Alt+L { spawn "qs" "-c" "noctalia-shell" "ipc" "call" "lockScreen" "lock"; }
' $NIRI

cat << EOF >> $NIRI
window-rule {
  geometry-corner-radius 20
  clip-to-geometry true
}
debug {
  honor-xdg-activation-with-invalid-serial
}
layer-rule {
  match namespace="^noctalia-overview*"
  place-within-backdrop true
}
cursor {
    hide-when-typing
}
spawn-at-startup "qs" "-c" "noctalia-shell"
prefer-no-csd
EOF

mkdir -p $HOME/.config/niri
mv $NIRI ./.config/niri/

# Services \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
systemctl enable ly
